import { Listing } from "@/types";

export const mockListings: Listing[] = [
  // INTERNSHIPS
  {
    id: "int-001",
    title: "Frontend Developer Intern",
    company: "Systems Limited",
    location: ["lahore"],
    category: "internships",
    tags: ["React", "TypeScript", "Next.js"],
    description:
      "Join our team to build cutting-edge web applications. You'll work alongside senior engineers on real-world projects serving millions of users.",
    deadline: "2025-06-15",
    salary: "PKR 25,000/month",
    duration: "3 months",
    link: "https://systemsltd.com/careers",
    featured: true,
    postedAt: "2025-05-01",
    type: "On-site",
    level: "Undergraduate",
  },
  {
    id: "int-002",
    title: "Data Science Intern",
    company: "Arbisoft",
    location: ["lahore"],
    category: "internships",
    tags: ["Python", "ML", "TensorFlow"],
    description:
      "Work on AI/ML projects that impact real users. You'll analyze datasets, build models, and deploy solutions.",
    deadline: "2025-06-20",
    salary: "PKR 30,000/month",
    duration: "6 months",
    link: "https://arbisoft.com/careers",
    featured: false,
    postedAt: "2025-04-28",
    type: "Hybrid",
    level: "Graduate",
  },
  {
    id: "int-003",
    title: "Backend Engineer Intern",
    company: "10Pearls",
    location: ["islamabad"],
    category: "internships",
    tags: ["Node.js", "PostgreSQL", "AWS"],
    description:
      "Build scalable APIs and microservices for our global SaaS platform. Great mentorship guaranteed.",
    deadline: "2025-07-01",
    salary: "PKR 28,000/month",
    duration: "3 months",
    link: "https://10pearls.com/careers",
    featured: true,
    postedAt: "2025-04-30",
    type: "On-site",
    level: "Undergraduate",
  },
  {
    id: "int-004",
    title: "Mobile App Intern",
    company: "Confiz",
    location: ["lahore"],
    category: "internships",
    tags: ["Flutter", "Dart", "Firebase"],
    description:
      "Develop cross-platform mobile apps. Excellent learning environment with real client projects.",
    deadline: "2025-06-25",
    salary: "PKR 22,000/month",
    duration: "3 months",
    link: "https://confiz.com/careers",
    featured: false,
    postedAt: "2025-04-25",
    type: "On-site",
    level: "Undergraduate",
  },
  {
    id: "int-005",
    title: "UI/UX Design Intern",
    company: "Netsol Technologies",
    location: ["lahore"],
    category: "internships",
    tags: ["Figma", "Adobe XD", "Prototyping"],
    description:
      "Design beautiful user interfaces for fintech products used globally. Work with product designers.",
    deadline: "2025-06-10",
    salary: "PKR 20,000/month",
    duration: "2 months",
    link: "https://netsol.com/careers",
    featured: false,
    postedAt: "2025-04-22",
    type: "On-site",
    level: "Undergraduate",
  },
  {
    id: "int-006",
    title: "Software Engineering Intern",
    company: "Devsinc",
    location: ["islamabad", "lahore"],
    category: "internships",
    tags: ["Ruby on Rails", "React", "Docker"],
    description:
      "Full-stack development internship at a fast-growing startup. Ship features from day one.",
    deadline: "2025-07-15",
    salary: "PKR 35,000/month",
    duration: "6 months",
    link: "https://devsinc.com/careers",
    featured: true,
    postedAt: "2025-05-02",
    type: "Remote",
    level: "Undergraduate",
  },
  {
    id: "int-007",
    title: "Cybersecurity Intern",
    company: "TechVista",
    location: ["karachi"],
    category: "internships",
    tags: ["Networking", "Ethical Hacking", "SIEM"],
    description:
      "Learn offensive and defensive security techniques in a professional SOC environment.",
    deadline: "2025-06-30",
    salary: "PKR 26,000/month",
    duration: "3 months",
    link: "https://techvista.net/careers",
    featured: false,
    postedAt: "2025-04-20",
    type: "On-site",
    level: "Undergraduate",
  },
  {
    id: "int-008",
    title: "AI Research Intern",
    company: "LUMS NLP Lab",
    location: ["lahore"],
    category: "internships",
    tags: ["NLP", "Python", "Transformers"],
    description:
      "Research-focused internship at LUMS. Work on Urdu NLP and multilingual AI models.",
    deadline: "2025-06-05",
    salary: "Stipend provided",
    duration: "4 months",
    link: "https://lums.edu.pk/research",
    featured: true,
    postedAt: "2025-04-15",
    type: "On-site",
    level: "Graduate",
  },

  // HACKATHONS
  {
    id: "hack-001",
    title: "PakHack 2025",
    company: "NUST & HEC",
    location: ["islamabad"],
    category: "hackathons",
    tags: ["AI/ML", "HealthTech", "FinTech"],
    description:
      "Pakistan's largest hackathon! 48 hours to build solutions for national challenges. Open to all students across Pakistan.",
    deadline: "2025-06-30",
    prize: "PKR 1,000,000",
    duration: "48 hours",
    link: "#",
    featured: true,
    postedAt: "2025-04-30",
    type: "In-person",
    level: "All levels",
  },
  {
    id: "hack-002",
    title: "LahoreTech Hackathon",
    company: "FAST NUCES",
    location: ["lahore"],
    category: "hackathons",
    tags: ["Web3", "Blockchain", "DeFi"],
    description:
      "Build decentralized applications in 36 hours. Mentors from leading blockchain companies will guide you.",
    deadline: "2025-07-10",
    prize: "PKR 500,000",
    duration: "36 hours",
    link: "#",
    featured: false,
    postedAt: "2025-05-01",
    type: "In-person",
    level: "All levels",
  },
  {
    id: "hack-003",
    title: "Google Solution Challenge",
    company: "Google",
    location: ["worldwide"],
    category: "hackathons",
    tags: ["Google Cloud", "Android", "AI"],
    description:
      "Build apps using Google technologies to address one of the UN's 17 Sustainable Development Goals.",
    deadline: "2025-07-20",
    prize: "$10,000 + trip to Google HQ",
    duration: "3 months",
    link: "https://developers.google.com/community/gdsc-solution-challenge",
    featured: true,
    postedAt: "2025-04-10",
    type: "Online",
    level: "Undergraduate",
  },
  {
    id: "hack-004",
    title: "MetroHack Karachi",
    company: "IBA Karachi",
    location: ["karachi"],
    category: "hackathons",
    tags: ["EdTech", "AgriTech", "Smart Cities"],
    description:
      "24-hour hackathon focused on solving Pakistan's urban challenges through technology.",
    deadline: "2025-06-15",
    prize: "PKR 300,000",
    duration: "24 hours",
    link: "#",
    featured: false,
    postedAt: "2025-04-18",
    type: "In-person",
    level: "All levels",
  },
  {
    id: "hack-005",
    title: "NASA Space Apps Challenge",
    company: "NASA",
    location: ["worldwide", "lahore"],
    category: "hackathons",
    tags: ["Space Tech", "Data Visualization", "AI"],
    description:
      "Join the world's largest hackathon organized by NASA. Lahore is an official local event host.",
    deadline: "2025-10-05",
    prize: "Global recognition + prizes",
    duration: "48 hours",
    link: "https://www.spaceappschallenge.org",
    featured: true,
    postedAt: "2025-05-01",
    type: "Hybrid",
    level: "All levels",
  },

  // COMPETITIONS
  {
    id: "comp-001",
    title: "ICPC Regional Contest",
    company: "ACM-ICPC",
    location: ["lahore", "islamabad"],
    category: "competitions",
    tags: ["Algorithms", "Data Structures", "C++"],
    description:
      "International Collegiate Programming Contest — the most prestigious competitive programming competition. Regional heats in Pakistan.",
    deadline: "2025-09-01",
    prize: "World Finals Qualification",
    duration: "5 hours",
    link: "https://icpc.global",
    featured: true,
    postedAt: "2025-04-25",
    type: "In-person",
    level: "Undergraduate",
  },
  {
    id: "comp-002",
    title: "CFA Investment Research Challenge",
    company: "CFA Institute",
    location: ["karachi", "lahore"],
    category: "competitions",
    tags: ["Finance", "Equity Research", "Valuation"],
    description:
      "Research and analyze a publicly traded company and present your investment thesis to a panel of CFA charterholders.",
    deadline: "2025-08-01",
    prize: "Global finalist trip + scholarship",
    duration: "3 months",
    link: "https://cfainstitute.org",
    featured: false,
    postedAt: "2025-04-20",
    type: "Hybrid",
    level: "Undergraduate",
  },
  {
    id: "comp-003",
    title: "Imagine Cup",
    company: "Microsoft",
    location: ["worldwide"],
    category: "competitions",
    tags: ["Azure", "AI", "Social Impact"],
    description:
      "Microsoft's global student technology competition. Build a project that positively impacts the world.",
    deadline: "2025-07-31",
    prize: "$100,000 + mentorship",
    duration: "Months",
    link: "https://imaginecup.microsoft.com",
    featured: true,
    postedAt: "2025-04-05",
    type: "Online",
    level: "All levels",
  },

  // JOBS
  {
    id: "job-001",
    title: "Junior Frontend Developer",
    company: "Arbisoft",
    location: ["lahore"],
    category: "jobs",
    tags: ["React", "JavaScript", "CSS"],
    description:
      "Join a world-class team building products for global clients. Excellent growth path and benefits package.",
    salary: "PKR 80,000–120,000/month",
    link: "https://arbisoft.com/careers",
    featured: true,
    postedAt: "2025-05-01",
    type: "Full-time",
    level: "Entry Level",
  },
  {
    id: "job-002",
    title: "Python Developer",
    company: "Contour Software",
    location: ["lahore", "islamabad", "karachi"],
    category: "jobs",
    tags: ["Python", "Django", "REST APIs"],
    description:
      "Build enterprise software solutions for Canadian clients. Competitive salary and remote work available.",
    salary: "PKR 100,000–150,000/month",
    link: "https://contour-software.com/careers",
    featured: false,
    postedAt: "2025-04-29",
    type: "Full-time",
    level: "Mid Level",
  },
  {
    id: "job-003",
    title: "DevOps Engineer",
    company: "PureLogics",
    location: ["lahore"],
    category: "jobs",
    tags: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
    description:
      "Manage cloud infrastructure for high-traffic applications. Great team and remote-friendly culture.",
    salary: "PKR 150,000–200,000/month",
    link: "https://purelogics.net/careers",
    featured: true,
    postedAt: "2025-04-28",
    type: "Full-time",
    level: "Senior",
  },
  {
    id: "job-004",
    title: "Mobile Developer (React Native)",
    company: "Techlets",
    location: ["islamabad"],
    category: "jobs",
    tags: ["React Native", "iOS", "Android"],
    description:
      "Build cross-platform mobile apps for US and UK clients. Strong communication skills required.",
    salary: "PKR 90,000–130,000/month",
    link: "#",
    featured: false,
    postedAt: "2025-04-27",
    type: "Full-time",
    level: "Mid Level",
  },
  {
    id: "job-005",
    title: "QA Engineer",
    company: "Tkxel",
    location: ["lahore"],
    category: "jobs",
    tags: ["Selenium", "Cypress", "Test Automation"],
    description:
      "Ensure quality across web and mobile products. Opportunity to grow into SDET role.",
    salary: "PKR 70,000–100,000/month",
    link: "https://tkxel.com/careers",
    featured: false,
    postedAt: "2025-04-25",
    type: "Full-time",
    level: "Entry Level",
  },
  {
    id: "job-006",
    title: "Product Manager",
    company: "Careem",
    location: ["karachi", "lahore"],
    category: "jobs",
    tags: ["Product Strategy", "Agile", "Analytics"],
    description:
      "Drive product strategy for one of MENA's leading super apps. You'll own features used by millions.",
    salary: "PKR 250,000–400,000/month",
    link: "https://careem.com/careers",
    featured: true,
    postedAt: "2025-05-02",
    type: "Full-time",
    level: "Senior",
  },

  // MOCK TESTS
  {
    id: "mock-001",
    title: "MDCAT Full Mock Test Series",
    company: "PingMe Prep",
    location: ["lahore", "islamabad", "karachi", "sahiwal"],
    category: "mock-tests",
    tags: ["Biology", "Chemistry", "Physics", "English"],
    description:
      "Complete MDCAT preparation with 10 full mock tests, chapter-wise quizzes, and detailed performance analytics.",
    link: "#",
    featured: true,
    postedAt: "2025-04-01",
    type: "Online",
    level: "Pre-Medical",
    deadline: "Ongoing",
  },
  {
    id: "mock-002",
    title: "ECAT Engineering Aptitude Test",
    company: "PingMe Prep",
    location: ["lahore", "islamabad", "karachi"],
    category: "mock-tests",
    tags: ["Math", "Physics", "Chemistry", "English"],
    description:
      "Comprehensive ECAT preparation covering all universities including UET, NUST, GIKI. 15 mock tests included.",
    link: "#",
    featured: false,
    postedAt: "2025-04-01",
    type: "Online",
    level: "Pre-Engineering",
    deadline: "Ongoing",
  },
  {
    id: "mock-003",
    title: "GRE Prep Course",
    company: "PingMe Prep",
    location: ["worldwide"],
    category: "mock-tests",
    tags: ["Verbal", "Quant", "AWA"],
    description:
      "Boost your GRE score with adaptive mock tests, personalized study plans, and expert guidance.",
    link: "#",
    featured: false,
    postedAt: "2025-04-01",
    type: "Online",
    level: "Graduate",
    deadline: "Ongoing",
  },
  {
    id: "mock-004",
    title: "CSS/PMS Written Exam Mock Tests",
    company: "PingMe Prep",
    location: ["lahore", "islamabad"],
    category: "mock-tests",
    tags: ["Essay", "General Knowledge", "Pakistan Affairs"],
    description:
      "Prepare for CSS and PMS exams with subject-wise mocks, essay practice, and previous year papers.",
    link: "#",
    featured: true,
    postedAt: "2025-04-01",
    type: "Online",
    level: "All levels",
    deadline: "Ongoing",
  },

  // INTERVIEW PREP
  {
    id: "iv-001",
    title: "DSA Interview Bootcamp",
    company: "PingMe Prep",
    location: ["worldwide"],
    category: "interview-prep",
    tags: ["Arrays", "Trees", "Graphs", "DP"],
    description:
      "Crack FAANG and top tech company interviews. 150+ curated problems with video explanations and mock interviews.",
    link: "#",
    featured: true,
    postedAt: "2025-04-01",
    type: "Online",
    level: "All levels",
    deadline: "Ongoing",
  },
  {
    id: "iv-002",
    title: "System Design Interview Guide",
    company: "PingMe Prep",
    location: ["worldwide"],
    category: "interview-prep",
    tags: ["Scalability", "Databases", "Microservices"],
    description:
      "Master system design for senior engineering roles. Case studies from WhatsApp, Uber, Twitter architectures.",
    link: "#",
    featured: false,
    postedAt: "2025-04-01",
    type: "Online",
    level: "Mid–Senior",
    deadline: "Ongoing",
  },
  {
    id: "iv-003",
    title: "HR Interview & Soft Skills",
    company: "PingMe Prep",
    location: ["lahore", "karachi", "islamabad"],
    category: "interview-prep",
    tags: ["Communication", "Leadership", "Behavioral"],
    description:
      "Prepare for HR rounds with STAR method practice, mock HR sessions, and personalized feedback.",
    link: "#",
    featured: false,
    postedAt: "2025-04-01",
    type: "Online",
    level: "All levels",
    deadline: "Ongoing",
  },
  {
    id: "iv-004",
    title: "Frontend Interview Prep",
    company: "PingMe Prep",
    location: ["worldwide"],
    category: "interview-prep",
    tags: ["JavaScript", "React", "CSS", "Performance"],
    description:
      "Deep-dive into JS fundamentals, React patterns, and CSS tricks frequently asked in tech interviews.",
    link: "#",
    featured: true,
    postedAt: "2025-04-01",
    type: "Online",
    level: "Junior–Mid",
    deadline: "Ongoing",
  },
];

export const categoryConfig = {
  all: { label: "All", emoji: "🌐", color: "bg-gray-100 text-gray-700" },
  internships: {
    label: "Internships",
    emoji: "💼",
    color: "bg-blue-100 text-blue-700",
  },
  hackathons: {
    label: "Hackathons",
    emoji: "⚡",
    color: "bg-purple-100 text-purple-700",
  },
  competitions: {
    label: "Competitions",
    emoji: "🏆",
    color: "bg-amber-100 text-amber-700",
  },
  jobs: { label: "Jobs", emoji: "🚀", color: "bg-green-100 text-green-700" },
  "mock-tests": {
    label: "Mock Tests",
    emoji: "📝",
    color: "bg-pink-100 text-pink-700",
  },
  "interview-prep": {
    label: "Interview Prep",
    emoji: "🎯",
    color: "bg-orange-100 text-orange-700",
  },
};

export const locationConfig = {
  all: { label: "All Locations", flag: "🌍" },
  lahore: { label: "Lahore", flag: "🏙️" },
  islamabad: { label: "Islamabad", flag: "🏛️" },
  karachi: { label: "Karachi", flag: "🌊" },
  sahiwal: { label: "Sahiwal", flag: "🌾" },
  worldwide: { label: "Worldwide", flag: "🌐" },
  remote: { label: "Remote", flag: "💻" },
};
